### PR TITLE
Update data.json to add a new gradient

### PR DESCRIPTION
**Pull request by IroncladDev**
I added a new gradient to your GradientKing project.
Maybe in the future, could you add Accounts instead of going through the painful process to make a pull request?

Great job, btw.

### CODE REVIEW

**Comment by saviomartin** [comment]
Yeah bro, I'm working on that. The main problem is the duplication of same gradient. It is a little hard to manage, so maybe it will take time to share using accounts. Thanks

**Review by saviomartin — CHANGES_REQUESTED** [review]
There is no GitHub account named *LeviathanProgramming*. Please change this.

**Comment by Conner1115** [comment]
Whoops, sorry, it was Conner1115.

**Comment by saviomartin** [comment]
Then change it brother

**Pull request closed without merging**
